### ISSUE TITLE
Empty Array has JsonSimpleConverter crash

### ISSUE THREAD

**Issue by chriline** [lensesio/stream-reactor#1015]
Hi,

we're trying to run the MQTT source connector with _JsonSimpleConverter_, because it seems to play nice with AWS' AVRO converter https://github.com/awslabs/aws-glue-schema-registry in general. However _JsonSimpleConverter_ appears to be struggling with empty arrays (see below error logs).

### What version of the Stream Reactor are you reporting this issue for?
5.0.1 (https://github.com/lensesio/stream-reactor/releases/tag/5.0.1)

### What is the expected behaviour?
No crash.

### What was observed?
JsonSimpleConverter crashes processing JSON with an empty array.
```
{
    /* ... */
    "compositions": [],
    /* ... */
}
```
 
```
2023-12-21 14:27:51,282 WARN  [MQTT Call: MY_TOPIC] [com.datamountaineer.streamreactor.connect.mqtt.source.MqttManager] [messageArrived:147] Error is handled. Message will be lost! Id = 0 on topic=MY_TOPIC
2023-12-21 14:27:51,333 INFO  [MQTT Call: MY_TOPIC] [com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter$] [handleArray:121] handleArray(name=compositions, arr=List()) # added custom log to aid troubleshooting
2023-12-21 14:27:51,333 ERROR [MQTT Call: MY_TOPIC] [com.datamountaineer.streamreactor.connect.mqtt.source.MqttManager] [messageArrived:145] Error handling message with id:0 on topic:MY_TOPIC
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:662)
	at scala.collection.immutable.Nil$.head(List.scala:661)
	at com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter$.handleArray(JsonSimpleConverter.scala:123)
	at com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter$.convert(JsonSimpleConverter.scala:103)
	at com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter$.$anonfun$handleObject$1(JsonSimpleConverter.scala:136)
	at scala.collection.immutable.List.map(List.scala:250)
	at com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter$.handleObject(JsonSimpleConverter.scala:134)
	at com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter$.convert(JsonSimpleConverter.scala:117)
	at com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter$.convert(JsonSimpleConverter.scala:98)
	at com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter.convert(JsonSimpleConverter.scala:46)
	at com.datamountaineer.streamreactor.connect.mqtt.source.MqttManager.messageArrived(MqttManager.scala:122)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:519)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:417)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:214)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### What is your connector properties configuration (my-connector.properties)?
```
name=lenses-5-mqtt-source
connector.class=com.datamountaineer.streamreactor.connect.mqtt.source.MqttSourceConnector
tasks.max=1
connect.mqtt.hosts=wss://my-mqtt-broker:1910
connect.mqtt.username=my-username
connect.mqtt.password=my-password
connect.mqtt.service.quality=2
connect.mqtt.clean=true
connect.mqtt.client.id=my-client-id
connect.mqtt.kcql=INSERT INTO test SELECT * FROM MyTestMqttTopic WITHCONVERTER=`com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter`
```

Thanks a bunch

**Comment by davidsloan** [comment]
Hello @chriline,

The JsonSimpleConverter is designed to make an attempt at converting incoming JSON into a Connect Struct, ultimately generating Avro records for your Kafka topic if you use AvroConverter for your connector instance. While it provides a reasonable default, for optimal performance and customization based on your payload scenarios, it's recommended to write and integrate your own converter.

Here's why:

Consider two JSON payloads:

```
    ...
    "compositions": ["Concerto No 5", "Mambo No 6"],
    ...
```

```
    ...
    "compositions": [],
    ...
```

Because no type information is available in Json, these two entries would result in the creation of two different schemas (one containing the string schema type information, and one either skipping the field or with a null schema).

Since you are familiar with your domain and payload structure, it's advisable to create a custom converter to precisely match your requirements. Many users and customers have already followed this approach successfully.

To implement your converter, you can check out the project and create a new module depending on `kafka-connect-common` and implement `io.lenses.streamreactor.connect.converters.source.Converter`.  Ensure that the resulting JAR is placed in your plugin.path location.

If needed, we offer client engagements as part of our services to assist you in scenarios like this. Feel free to reach out if you require further assistance.

I will however create a ticket internally to ensure that this issue triggers a clearer error message.
