### ISSUE TITLE
FTP Source - large files can make the connector crash

### ISSUE THREAD

**Issue by jbruggem** [lensesio/stream-reactor#462]
Version: Confluent Platform 3.3

### What is the expected behaviour?

When reading a big file from an FTP source, it is processed correctly

### What was observed?

When reading a file from an FTP server with the FTP Source Connector, the connector crashes (out of memory).

From what I understand, the whole file is read in memory directly, meaning the big files will be an issue even if I increase the memory available to my connector.

Is this by design ? Is there a way around this ? Could we expect the source connector to become better with big files ?

```
java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:3236)
    at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
    at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
    at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
    at org.apache.commons.net.io.Util.copyStream(Util.java:124)
    at org.apache.commons.net.ftp.FTPClient._retrieveFile(FTPClient.java:1924)
    at org.apache.commons.net.ftp.FTPClient.retrieveFile(FTPClient.java:1889)
    at com.datamountaineer.streamreactor.connect.ftp.source.FtpMonitor.fetch(FtpMonitor.scala:74)
    at com.datamountaineer.streamreactor.connect.ftp.source.FtpMonitor$$anonfun$fetchFromMonitoredPlaces$3.apply(FtpMonitor.scala:142)
    at com.datamountaineer.streamreactor.connect.ftp.source.FtpMonitor$$anonfun$fetchFromMonitoredPlaces$3.apply(FtpMonitor.scala:142)
    at scala.collection.immutable.Stream.flatMap(Stream.scala:489)
    at com.datamountaineer.streamreactor.connect.ftp.source.FtpMonitor.fetchFromMonitoredPlaces(FtpMonitor.scala:142)
    at com.datamountaineer.streamreactor.connect.ftp.source.FtpMonitor$$anonfun$poll$1$$anonfun$apply$1.apply(FtpMonitor.scala:190)
    at com.datamountaineer.streamreactor.connect.ftp.source.FtpMonitor$$anonfun$poll$1$$anonfun$apply$1.apply(FtpMonitor.scala:189)
    at scala.collection.immutable.Stream.flatMap(Stream.scala:489)
    at com.datamountaineer.streamreactor.connect.ftp.source.FtpMonitor$$anonfun$poll$1.apply(FtpMonitor.scala:189)
    at com.datamountaineer.streamreactor.connect.ftp.source.FtpMonitor$$anonfun$poll$1.apply(FtpMonitor.scala:189)
    at scala.util.Try$.apply(Try.scala:192)
    at com.datamountaineer.streamreactor.connect.ftp.source.FtpMonitor.poll(FtpMonitor.scala:189)
    at com.datamountaineer.streamreactor.connect.ftp.source.FtpSourcePoller.fetchRecords(FtpSourceTask.scala:78)
    at com.datamountaineer.streamreactor.connect.ftp.source.FtpSourcePoller.poll(FtpSourceTask.scala:69)
    at com.datamountaineer.streamreactor.connect.ftp.source.FtpSourceTask.poll(FtpSourceTask.scala:121)
    at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:163)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
``

**Comment by nicolas-coulon** [comment]
For your information, we are working on a fix. euranova/stream-reactor#1 .

We will submit a pull request to you when happy with the result. In the mean time, feel free to participate. Any input would be very appreciated.

**Comment by JoeInigo** [comment]
Hi,
I try to extract a xml file from a remote server using Apache FTPclient and size of the file varies from 2 to 3 GB. When the retrieveFile(FTPClient) method is called, it returns the error message.  java.lang.OutOfMemoryError: Requested array size exceeds VM limit 
   at java.util.Arrays.copyOf(Arrays.java:2271)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:113)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:140)
        at org.apache.commons.net.io.Util.copyStream(Util.java:119)
        at org.apache.commons.net.ftp.FTPClient.retrieveFile(FTPClient.java:1286)
The application is deployed in Jboss app server and the maximum heap is set to 4GB at present. The application uses Java language to do the same. Request your help to resolve the issues.

**Comment by andrewstevenson** [comment]
@JoeInigo Increase the heap space available to the Connect workers.

**Comment by JoeInigo** [comment]
@andrewstevenson, Yes. I have tried that.  The buffer size of the OutputStream exceeds while calling the retrieve the file. Any suggestions like reading the contents by parts or file slices and then storing them

**Comment by andrewstevenson** [comment]
@JoeInigo "The application is deployed in Jboss app server"? Which version of the FTP Kafka Connector or you running?

**Comment by JoeInigo** [comment]
Yes.. The Application is deployed in Jboss. We are not using FTP Kafka connector rather using FTPClient from org.apache.commons.net.ftp version 2.0

**Comment by andrewstevenson** [comment]
@JoeInigo We can't help you I'm afraid. I would ask on stackoverflow as we aren't supporting the FTPClient and your custom app.

**Comment by JoeInigo** [comment]
@andrewstevenson , Thanks. Is there any other FTP clients that can be used for this case.
