### ISSUE TITLE
MqttException - java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Mourish** [lensesio/stream-reactor#554]
**Kafka Version: kafka_2.11-2.1.1
export KAFKA_HEAP_OPTS="-Xms256M -Xmx2G"
Ubuntu Server Config = 16GB RAM, 30 GB HD**

In connect-avro-distributed.properties console i was getting a following bug

**MqttException (0) - java.lang.OutOfMemoryError: Java heap space**
at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:220)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
at org.apache.avro.util.Utf8.setByteLength(Utf8.java:78)
at org.apache.avro.io.BinaryDecoder.readString(BinaryDecoder.java:261)
at org.apache.avro.io.ResolvingDecoder.readString(ResolvingDecoder.java:201)
at org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:422)
at org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:414)
at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:181)
at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:153)
at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:232)
at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:222)
at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:175)
at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:153)
at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:145)
at com.datamountaineer.streamreactor.connect.converters.source.AvroConverter.convert(AvroConverter.scala:52)
at com.datamountaineer.streamreactor.connect.mqtt.source.MqttManager.messageArrived(MqttManager.scala:73)
at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:499)
at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:402)
at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:206)

**Comment by stheppi** [comment]
Hi @Mourish 
  From the logs I see you are expecting Avro messages over MQTT. Is that the case? What is your configuration for the source? Why did you set the max memory to only 2GB? 
  Did you try to investigate what happens when you increase your memory limit?

**Comment by andrewstevenson** [comment]
closing due to inactivity
