### ISSUE TITLE
kafka-connect-influxdb does not work with message keys as strings

### ISSUE THREAD

**Issue by alfamegaxq** [lensesio/stream-reactor#632]
Stream Reactor version 1.2.3-2.1.0

Using docker image confluentinc/cp-kafka-connect-base:5.3.1

influxdb latest docker image

I have added influx sink connector with the following configurations:

```
connector.class=com.datamountaineer.streamreactor.connect.influx.InfluxSinkConnector
connect.influx.db=traffic
errors.tolerance = all
tasks.max=15
topics=traffic
connect.influx.kcql=INSERT INTO traffic SELECT * FROM traffic WITHTIMESTAMP sys_time()
connect.influx.username=influx
internal.key.converter.schemas.enable=false
use.schema=false
connect.influx.url=http://influxdb:8086
key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
value.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.storage.StringConverter
key.converter=org.apache.kafka.connect.storage.StringConverter
```

message to be consumed:

```
{
    "topic": "traffic",
    "key": "5f00f94b725a4a7381a68d82abeb3f05958f52b816ba43afbff0c50d082581e6",
    "value": "{\"id\":\"123456\",\"lid\":\"5f00f94b725a4a7381a68d82abeb3f05958f52b816ba43afbff0c50d082581e6\",\"hid\":\"999\",\"timestamp\":1573649618632,\"traffic\":0}",
    "partition": 0,
    "offset": 0
  },
```

on connector message consume the following error is received:

```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('f' (code 102)): Expected space separating root-level values
 at [Source: (String)"5f00f94b725a4a7381a68d82abeb3f05958f52b816ba43afbff0c50d082581e6"; line: 1, column: 3]
	at com.datamountaineer.streamreactor.connect.errors.ThrowErrorPolicy.handle(ErrorPolicy.scala:58)
	at com.datamountaineer.streamreactor.connect.errors.ErrorHandler$class.handleError(ErrorHandler.scala:83)
	at com.datamountaineer.streamreactor.connect.errors.ErrorHandler$class.handleTry(ErrorHandler.scala:64)
	at com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter.handleTry(InfluxDbWriter.scala:29)
	at com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter.write(InfluxDbWriter.scala:43)
	at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask$$anonfun$put$2.apply(InfluxSinkTask.scala:77)
	at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask$$anonfun$put$2.apply(InfluxSinkTask.scala:77)
	at scala.Option.foreach(Option.scala:257)
	at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask.put(InfluxSinkTask.scala:77)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
```

Isn't it possible to consume messages with string keys?

**Comment by andrewstevenson** [comment]
@alfamegaxq you are using the wrong converters.

https://docs.lenses.io/connectors/sink/influx.html#schema-string-and-a-json-payload

**Comment by alfamegaxq** [comment]
@andrewstevenson 
```
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter=org.apache.kafka.connect.json.JsonConverter
```

same error.

```
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter=org.apache.kafka.connect.storage.StringConverter
```

same error.

the documentation says nothing about using:
```
key.converter=org.apache.kafka.connect.storage.StringConverter
```

is it a requirement to have topic with JSON key?
