### ISSUE TITLE
hive sink: can not seek hive table by kafka-connect-hive

### ISSUE THREAD

**Issue by littleqiqi** [lensesio/stream-reactor#635]
# Issue Guidelines

Please review these questions before submitting any issue?

### What version of the Stream Reactor are you reporting this issue for?
kafka-connect-hive-1.2.1-2.1.0

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
Apache Kafka 2.11-2.1.0
Confluent-5.1.0
Apache Hive 2.1.1
Java 1.8
CDH-6.3.0
### Have you read the [docs](https://docs.lenses.io/connectors/)?
yes
### What is the expected behaviour?
I can see that hive has data，such as“New York NY 8538000 USA”

### What was observed?

`ERROR Error seeking table DatabaseName(hive_connect).table (com.landoop.streamreactor.connect.hive.sink.staging.OffsetSeeker:44)
[2019-12-07 12:55:09,428] ERROR Error opening hive sink writer (com.landoop.streamreactor.connect.hive.sink.HiveSinkTask:79)

### What is your Connect cluster configuration (connect-avro-distributed.properties)?
{
    "name": "hive-sink-example",
    "config": {
        "name": "hive-sink-example",
        "connector.class": "com.landoop.streamreactor.connect.hive.sink.HiveSinkConnector",
        "tasks.max": 1,
        "topics": "hive_sink",
        "connect.hive.kcql": "insert into cities_orc select * from hive_sink AUTOCREATE PARTITIONBY state STOREAS ORC WITH_FLUSH_INTERVAL = 10 WITH_PARTITIONING = DYNAMIC",
        "connect.hive.database.name": "hive_connect",
        "connect.hive.hive.metastore": "thrift",
        "connect.hive.hive.metastore.uris": "thrift://10.195.186.30:9083",
        "connect.hive.fs.defaultFS": "hdfs://10.195.186.30:9001",
        "connect.hive.error.policy": "NOOP",
        "connect.progress.enabled": true
    }
}
send by Postman
by the way, I use 'hdfs://10.195.186.30:8020' too.

### What is your connector properties configuration (my-connector.properties)?
default

### Please provide full log files (redact and sensitive information)
[2019-12-07 12:55:07,926] INFO ConsumerConfig values: 
	auto.commit.interval.ms = 5000
	auto.offset.reset = earliest
	bootstrap.servers = [localhost:9092]
	check.crcs = true
	client.dns.lookup = default
	client.id = 
	connections.max.idle.ms = 540000
	default.api.timeout.ms = 60000
	enable.auto.commit = false
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = connect-hive-sink-example
	heartbeat.interval.ms = 3000
	interceptor.classes = []
	internal.leave.group.on.close = true
	isolation.level = read_uncommitted
	key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = https
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
 (org.apache.kafka.clients.consumer.ConsumerConfig:279)
[2019-12-07 12:55:07,929] INFO Kafka version : 2.1.0-cp1 (org.apache.kafka.common.utils.AppInfoParser:109)
[2019-12-07 12:55:07,929] INFO Kafka commitId : 3bce825d5f759863 (org.apache.kafka.common.utils.AppInfoParser:110)
[2019-12-07 12:55:07,929] INFO Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:868)
[2019-12-07 12:55:08,026] INFO Trying to connect to metastore with URI thrift://10.195.186.30:9083 (hive.metastore:433)
[2019-12-07 12:55:08,039] INFO Opened a connection to metastore, current connections: 5 (hive.metastore:478)
[2019-12-07 12:55:08,050] INFO Connected to metastore. (hive.metastore:530)
[2019-12-07 12:55:08,070] INFO HiveSinkConfigDefBuilder values: 
	connect.hive.database.name = hive_connect
	connect.hive.fs.defaultFS = hdfs://10.195.186.30:9001
	connect.hive.hive.metastore = thrift
	connect.hive.hive.metastore.uris = thrift://10.195.186.30:9083
	connect.hive.kcql = insert into cities_orc select * from hive_sink AUTOCREATE PARTITIONBY state STOREAS ORC WITH_FLUSH_INTERVAL = 10 WITH_PARTITIONING = DYNAMIC
	connect.progress.enabled = true
 (com.landoop.streamreactor.connect.hive.sink.config.HiveSinkConfigDefBuilder:279)
[2019-12-07 12:55:08,071] INFO WorkerSinkTask{id=hive-sink-example-0} Sink task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask:303)
[2019-12-07 12:55:08,088] INFO Cluster ID: hMoN7KhnTiWm9I1IWNGUqg (org.apache.kafka.clients.Metadata:285)
[2019-12-07 12:55:08,088] INFO [Consumer clientId=consumer-8, groupId=connect-hive-sink-example] Discovered group coordinator 192.168.35.224:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:654)
[2019-12-07 12:55:08,100] INFO [Consumer clientId=consumer-8, groupId=connect-hive-sink-example] Revoking previously assigned partitions [] (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:458)
[2019-12-07 12:55:08,101] INFO [Consumer clientId=consumer-8, groupId=connect-hive-sink-example] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:486)
[2019-12-07 12:55:08,117] INFO [Consumer clientId=consumer-8, groupId=connect-hive-sink-example] Successfully joined group with generation 7 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:450)
[2019-12-07 12:55:08,117] INFO [Consumer clientId=consumer-8, groupId=connect-hive-sink-example] Setting newly assigned partitions [hive_sink-0] (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:289)
[2019-12-07 12:55:08,121] INFO [Consumer clientId=consumer-8, groupId=connect-hive-sink-example] Resetting offset for partition hive_sink-0 to offset 0. (org.apache.kafka.clients.consumer.internals.Fetcher:583)
[2019-12-07 12:55:09,427] ERROR Error seeking table DatabaseName(hive_connect).table (com.landoop.streamreactor.connect.hive.sink.staging.OffsetSeeker:44)
[2019-12-07 12:55:09,428] ERROR Error opening hive sink writer (com.landoop.streamreactor.connect.hive.sink.HiveSinkTask:79)
java.lang.IllegalArgumentException: Wrong FS: hdfs://cdh1:8020/user/hive/warehouse/hive_connect.db/cities_orc, expected: hdfs://10.195.186.30:9001
	at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:647)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:194)
	at org.apache.hadoop.hdfs.DistributedFileSystem.access$000(DistributedFileSystem.java:106)
	at org.apache.hadoop.hdfs.DistributedFileSystem$DirListingIterator.<init>(DistributedFileSystem.java:940)
	at org.apache.hadoop.hdfs.DistributedFileSystem$DirListingIterator.<init>(DistributedFileSystem.java:927)
	at org.apache.hadoop.hdfs.DistributedFileSystem$19.doCall(DistributedFileSystem.java:872)
	at org.apache.hadoop.hdfs.DistributedFileSystem$19.doCall(DistributedFileSystem.java:868)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.listLocatedStatus(DistributedFileSystem.java:886)
	at org.apache.hadoop.fs.FileSystem.listLocatedStatus(FileSystem.java:1694)
	at org.apache.hadoop.fs.FileSystem$6.<init>(FileSystem.java:1787)
	at org.apache.hadoop.fs.FileSystem.listFiles(FileSystem.java:1783)
	at com.landoop.streamreactor.connect.hive.HdfsUtils$RichFileSystem.ls(HdfsUtils.scala:11)
	at com.landoop.streamreactor.connect.hive.sink.staging.OffsetSeeker.seek(OffsetSeeker.scala:32)
	at com.landoop.streamreactor.connect.hive.sink.HiveSinkTask$$anonfun$open$2.apply(HiveSinkTask.scala:87)
	at com.landoop.streamreactor.connect.hive.sink.HiveSinkTask$$anonfun$open$2.apply(HiveSinkTask.scala:86)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at com.landoop.streamreactor.connect.hive.sink.HiveSinkTask.open(HiveSinkTask.scala:86)
	at com.landoop.streamreactor.connect.hive.sink.HiveSinkTask.open(HiveSinkTask.scala:76)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.openPartitions(WorkerSinkTask.java:613)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.access$1100(WorkerSinkTask.java:70)
	at org.apache.kafka.connect.runtime.WorkerSinkTask$HandleRebalance.onPartitionsAssigned(WorkerSinkTask.java:673)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:291)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:406)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:340)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:341)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1214)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1179)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1164)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:445)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:318)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2019-12-07 12:55:43,213] INFO Cluster ID: hMoN7KhnTiWm9I1IWNGUqg (org.apache.kafka.clients.Metadata:285)
[2019-12-07 12:56:07,925] ERROR WorkerSinkTask{id=hive-sink-example-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
java.lang.IllegalArgumentException: Wrong FS: hdfs://cdh1:8020/user/hive/warehouse/hive_connect.db/cities_orc, expected: hdfs://10.195.186.30:9001
	at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:647)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:194)
	at org.apache.hadoop.hdfs.DistributedFileSystem.access$000(DistributedFileSystem.java:106)
	at org.apache.hadoop.hdfs.DistributedFileSystem$DirListingIterator.<init>(DistributedFileSystem.java:940)
	at org.apache.hadoop.hdfs.DistributedFileSystem$DirListingIterator.<init>(DistributedFileSystem.java:927)
	at org.apache.hadoop.hdfs.DistributedFileSystem$19.doCall(DistributedFileSystem.java:872)
	at org.apache.hadoop.hdfs.DistributedFileSystem$19.doCall(DistributedFileSystem.java:868)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.listLocatedStatus(DistributedFileSystem.java:886)
	at org.apache.hadoop.fs.FileSystem.listLocatedStatus(FileSystem.java:1694)
	at org.apache.hadoop.fs.FileSystem$6.<init>(FileSystem.java:1787)
	at org.apache.hadoop.fs.FileSystem.listFiles(FileSystem.java:1783)
	at com.landoop.streamreactor.connect.hive.HdfsUtils$RichFileSystem.ls(HdfsUtils.scala:11)
	at com.landoop.streamreactor.connect.hive.sink.staging.OffsetSeeker.seek(OffsetSeeker.scala:32)
	at com.landoop.streamreactor.connect.hive.sink.HiveSinkTask$$anonfun$open$2.apply(HiveSinkTask.scala:87)
	at com.landoop.streamreactor.connect.hive.sink.HiveSinkTask$$anonfun$open$2.apply(HiveSinkTask.scala:86)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at com.landoop.streamreactor.connect.hive.sink.HiveSinkTask.open(HiveSinkTask.scala:86)
	at com.landoop.streamreactor.connect.hive.sink.HiveSinkTask.open(HiveSinkTask.scala:76)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.openPartitions(WorkerSinkTask.java:613)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.access$1100(WorkerSinkTask.java:70)
	at org.apache.kafka.connect.runtime.WorkerSinkTask$HandleRebalance.onPartitionsAssigned(WorkerSinkTask.java:673)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:291)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:406)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:340)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:341)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1214)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1179)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1164)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:445)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:318)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2019-12-07 12:56:07,934] ERROR WorkerSinkTask{id=hive-sink-example-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:178)

I promise that hive is running normally, But what is  Error seeking table DatabaseName(hive_connect).table

**Comment by davidsloan** [comment]
Closing due to deprecation of the hive connector.
