### ISSUE TITLE
Azure DocumentDB SDK deprecated - need to update before May 30 2020

### ISSUE THREAD

**Issue by brandonwittwer** [lensesio/stream-reactor#665]
https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-java.

I'm cloning now to see if there are any breaking changes, but I've never build scala before, so someone else could likely beat me to it.  Hopefully it's just  version change.  The latest version is 2.4.7

https://mvnrepository.com/artifact/com.microsoft.azure/azure-documentdb

**Comment by brandonwittwer** [comment]
It builds with the latest version, but I can't get the tests to run.  Anyone help me with that?  

an example of a failed test
`
- should handle json UPSERT with Eventual consistency level *** FAILED *** (1 millisecond)
  java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker
  at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:66)
  at com.sun.proxy.$Proxy7.isTypeMockable(Unknown Source)
  at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:29)
  at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
  at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:168)
  at org.mockito.internal.creation.MockSettingsImpl.confirm(MockSettingsImpl.java:162)
  at org.mockito.internal.MockitoCore.mock(MockitoCore.java:64)
  at org.mockito.Mockito.mock(Mockito.java:1694)
  at org.mockito.Mockito.mock(Mockito.java:1607)
  at org.scalatest.mockito.MockitoSugar$class.mock(MockitoSugar.scala:73)
  ...
  Cause: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in java.lang.CompoundEnumeration@59026d6d
  at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:101)
  at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:45)
  at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:18)
  at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:17)
  at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
  at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
  at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:168)
  at org.mockito.internal.creation.MockSettingsImpl.confirm(MockSettingsImpl.java:162)
  at org.mockito.internal.MockitoCore.mock(MockitoCore.java:64)
  at org.mockito.Mockito.mock(Mockito.java:1694)
  ...
  Cause: org.mockito.exceptions.base.MockitoInitializationException: Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)

Java               : 13
JVM vendor name    : Oracle Corporation
JVM vendor version : 13.0.1+9
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 13.0.1+9
JVM info           : mixed mode, sharing
OS name            : Windows 10
OS version         : 10.0
  at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:172)
  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
  at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166)
  at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:404)
  at java.base/java.lang.Class.newInstance(Class.java:591)
  at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:96)
  at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:45)
  ...
  Cause: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@1946e75   
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:316)
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:282)
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:250)
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:236)
  at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<clinit>(InlineByteBuddyMockMaker.java:102)
  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
  at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166)
  ...
  Cause: java.lang.reflect.InvocationTargetException:
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:567)
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:303)
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:282)
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:250)
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:236)
  at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<clinit>(InlineByteBuddyMockMaker.java:102)
  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  ...
  Cause: java.io.IOException: Can not attach to current VM
  at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.<init>(HotSpotVirtualMachine.java:75)
  at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:48)
  at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:69)
  at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:567)
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:303)
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:282)
`
