### ISSUE TITLE
kafka connector Elastic search 7

### ISSUE THREAD

**Issue by mgulli-voiptech** [lensesio/stream-reactor#666]
Hi,
I'm using stream-reactor 1.1.0 (but I've also tried with the latest one) but I can't connect to my ElasticSearch cloud instance (using https, no other chance).
This is my configuration:

`
connector.class=com.datamountaineer.streamreactor.connect.elastic6.ElasticSinkConnector
connect.elastic.use.http.username=elastic
connect.elastic.use.http.password=xxxxxxxxxxxx
tasks.max=5
topics=xxxxxxxxxx
connect.elastic.url=elasticsearch://xxxxxxxxxxxxxx.aws.cloud.es.io:9243
connect.elastic.kcql=INSERT INTO index SELECT * FROM xxxxx
connect.elastic.url.prefix=https
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter=org.apache.kafka.connect.json.JsonConverter
connect.elastic.use.http=HTTP
`
and this is the error:

`java.lang.IllegalArgumentException: Invalid uri, must be in format elasticsearch://host:port,host:port,...
	at com.sksamuel.elastic4s.ElasticsearchClientUri$$anonfun$2.apply(ElasticClient.scala:155)
	at com.sksamuel.elastic4s.ElasticsearchClientUri$$anonfun$2.apply(ElasticClient.scala:150)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at com.sksamuel.elastic4s.ElasticsearchClientUri$.apply(ElasticClient.scala:150)
	at com.datamountaineer.streamreactor.connect.elastic6.ElasticWriter$.apply(ElasticWriter.scala:39)
	at com.datamountaineer.streamreactor.connect.elastic6.ElasticSinkTask.start(ElasticSinkTask.scala:53)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:301)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:189)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.jav`

Now... is the elastic6 connector compatible with elasticsearch 7 in https? I'm doing wrong?
Thanks

Mario

**Comment by mgulli-voiptech** [comment]
Is the project still alive?

**Comment by andrewstevenson** [comment]
@mgulli-voiptech yes. Its still alive. We use the elastic4s version. So if your check this dependencies version you can see which elastic version it supports.

**Comment by johnathana** [comment]
@mgulli-voiptech  We now offer an elastic 7 sink connector. Closing this issue.
