### ISSUE TITLE
Duplicate tickets as #678, pending to remove

### ISSUE THREAD

**Issue by cph1c06** [lensesio/stream-reactor#677]
I'm attempting to use Cassandra on AWS Amazon Keyspaces and sink data from Kafka into it using the Cassandra Sink. Same exact sink configuration works with regular Cassandra, but fails on Amazon Keyspaces.

Sink properties:
```
{
  "name": "cassandra-sink-orders",
  "config": {
    "connector.class": "com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkConnector",
    "tasks.max": "1",
    "errors.log.enable": "true",
    "connect.cassandra.contact.points": "cassandra.ap-southeast-1.amazonaws.com",
    "connect.cassandra.port": "<redacted>,
    "loadBalancing.localDc": "<redacted>",
    "connect.cassandra.username": "<redacted>",
    "connect.cassandra.password": "<redacted>",
    "topics": "json-stream",
    "connect.cassandra.key.space": "lake",
    "connect.cassandra.kcql": "INSERT INTO test SELECT test as content FROM json-stream",
    "connect.cassandra.ssl.enabled": "true",
    "ssl.provider": "JDK",
    "ssl.trustStore": "/tmp/cassandra_truststore.jks",
    "ssl.trustStorePassword": "<redacted>"
  }
}

```

The sink is configured with JSON without schema. Target table is created with:

```
create keyspace if not exists lake with replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
CREATE TABLE lake.test (content text PRIMARY KEY);
```
JSON records in the topic match exactly the names and types of the fields in the target table.

When used with regular Cassandra above configuration works as expected. When configured to sink to Cassandra on Amazon Keyspace same configuration fails with the following error:
```
[2020-04-26 07:23:07,160] INFO Preparing statements for json-stream->test (com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter)
[2020-04-26 07:23:07,201] ERROR Encountered error Unsupported statement type class org.apache.cassandra.cql3.statements.UpdateStatement$ParsedInsertJson (com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter)
com.datastax.driver.core.exceptions.InvalidQueryException: Unsupported statement type class org.apache.cassandra.cql3.statements.UpdateStatement$ParsedInsertJson
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:49)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:86)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$3.apply(CassandraJsonWriter.scala:114)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$3.apply(CassandraJsonWriter.scala:105)
	at scala.util.Try$.apply(Try.scala:192)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.com$datamountaineer$streamreactor$connect$cassandra$sink$CassandraJsonWriter$$getPreparedStatement(CassandraJsonWriter.scala:105)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$cachePreparedStatements$2$$anonfun$2.apply(CassandraJsonWriter.scala:85)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$cachePreparedStatements$2$$anonfun$2.apply(CassandraJsonWriter.scala:81)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.ArrayBuffer.foldLeft(ArrayBuffer.scala:48)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$cachePreparedStatements$2.apply(CassandraJsonWriter.scala:81)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$cachePreparedStatements$2.apply(CassandraJsonWriter.scala:80)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.cachePreparedStatements(CassandraJsonWriter.scala:80)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.<init>(CassandraJsonWriter.scala:57)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraWriter$.apply(CassandraWriter.scala:43)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkTask.start(CassandraSinkTask.scala:64)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:300)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:189)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Unsupported statement type class org.apache.cassandra.cql3.statements.UpdateStatement$ParsedInsertJson
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:181)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:250)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:219)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
[2020-04-26 07:23:07,203] ERROR WorkerSinkTask{id=cassandra-sink-orders-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
java.lang.RuntimeException: com.datastax.driver.core.exceptions.InvalidQueryException: Unsupported statement type class org.apache.cassandra.cql3.statements.UpdateStatement$ParsedInsertJson
	at com.datamountaineer.streamreactor.connect.errors.ThrowErrorPolicy.handle(ErrorPolicy.scala:58)
	at com.datamountaineer.streamreactor.connect.errors.ErrorHandler$class.handleError(ErrorHandler.scala:83)
	at com.datamountaineer.streamreactor.connect.errors.ErrorHandler$class.handleTry(ErrorHandler.scala:64)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.handleTry(CassandraJsonWriter.scala:46)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.com$datamountaineer$streamreactor$connect$cassandra$sink$CassandraJsonWriter$$getPreparedStatement(CassandraJsonWriter.scala:118)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$cachePreparedStatements$2$$anonfun$2.apply(CassandraJsonWriter.scala:85)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$cachePreparedStatements$2$$anonfun$2.apply(CassandraJsonWriter.scala:81)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.ArrayBuffer.foldLeft(ArrayBuffer.scala:48)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$cachePreparedStatements$2.apply(CassandraJsonWriter.scala:81)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$cachePreparedStatements$2.apply(CassandraJsonWriter.scala:80)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.cachePreparedStatements(CassandraJsonWriter.scala:80)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.<init>(CassandraJsonWriter.scala:57)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraWriter$.apply(CassandraWriter.scala:43)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkTask.start(CassandraSinkTask.scala:64)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:300)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:189)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Unsupported statement type class org.apache.cassandra.cql3.statements.UpdateStatement$ParsedInsertJson
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:49)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:86)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$3.apply(CassandraJsonWriter.scala:114)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$3.apply(CassandraJsonWriter.scala:105)
	at scala.util.Try$.apply(Try.scala:192)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.com$datamountaineer$streamreactor$connect$cassandra$sink$CassandraJsonWriter$$getPreparedStatement(CassandraJsonWriter.scala:105)
	... 25 more
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Unsupported statement type class org.apache.cassandra.cql3.statements.UpdateStatement$ParsedInsertJson
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:181)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:250)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:219)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
[2020-04-26 07:23:07,204] ERROR WorkerSinkTask{id=cassandra-sink-orders-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
[2020-04-26 07:23:07,205] INFO Stopping Cassandra sink. (com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkTask)
```
Cassandra Sink version: 1.2.7-2.1.0. I'm using connect-distribute for tests currently.

**Comment by andrewstevenson** [comment]
@cph1c06 i don't understand what this has to do with Azure CosmosDB? Can you update the description and i think you have opened two duplicate tickets?

**Comment by cph1c06** [comment]
> @cph1c06 i don't understand what this has to do with Azure CosmosDB? Can you update the description and i think you have opened two duplicate tickets?

Thanks for reminding, I will close this ticket.
