### ISSUE TITLE
no NetworkModule installed for scheme "mqtts" 

### ISSUE THREAD

**Issue by kaustav1996** [lensesio/stream-reactor#721]
Hello Everyone,

So I am trying to connect to a secure mqtt broker i.e mqtts broker but getting the below error :

```
java.lang.IllegalArgumentException: no NetworkModule installed for scheme "mqtts" of URI "mqtts://maheshwntwpe.extwirepas.com"
	at org.eclipse.paho.client.mqttv3.internal.NetworkModuleService.validateURI(NetworkModuleService.java:72)
	at org.eclipse.paho.client.mqttv3.MqttConnectOptions.setServerURIs(MqttConnectOptions.java:589)
	at com.datamountaineer.streamreactor.connect.mqtt.connection.MqttClientConnectionFn$.buildBaseClient(MqttClientConnectionFn.scala:81)
	at com.datamountaineer.streamreactor.connect.mqtt.connection.MqttClientConnectionFn$.apply(MqttClientConnectionFn.scala:37)
	at com.datamountaineer.streamreactor.connect.mqtt.source.MqttSourceTask.$anonfun$start$6(MqttSourceTask.scala:78)
	at com.datamountaineer.streamreactor.connect.mqtt.source.MqttManager.<init>(MqttManager.scala:44)
	at com.datamountaineer.streamreactor.connect.mqtt.source.MqttSourceTask.start(MqttSourceTask.scala:78)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
My Config file : 
```
connector.class=com.datamountaineer.streamreactor.connect.mqtt.source.MqttSourceConnector
connect.mqtt.clean=true
errors.log.include.messages=false
connect.mqtt.timeout=3000
tasks.max=1
connect.mqtt.hosts=mqtts://maheshwntwpe.extwirepas.com:8883
connect.mqtt.converter.throw.on.error=false
connect.mqtt.error.policy=THROW
value.converter=org.apache.kafka.connect.json.JsonConverter
config.action.reload=restart
errors.log.enable=false
key.converter=org.apache.kafka.connect.json.JsonConverter
connect.mqtt.share.replicate=false
connect.mqtt.polling.timeout=1000
errors.retry.timeout=0
connect.mqtt.username=mqttmasteruser
connect.mqtt.retained.messages=false
connect.mqtt.max.retries=20
errors.retry.delay.max.ms=60000
connect.mqtt.service.quality=1
connect.progress.enabled=true
header.converter=org.apache.kafka.connect.json.JsonConverter
connect.mqtt.log.message=true
connect.mqtt.keep.alive=5000
name=Mqtt-kafka-connector-1
errors.tolerance=none
connect.mqtt.kcql=INSERT INTO test SELECT * FROM /test WITHCONVERTER=`com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter` WITHKEY(id)
connect.mqtt.retry.interval=60000
connect.mqtt.password=***********
connect.mqtt.client.id=kafka-mqtt-connector
```

If I replace mqtts:// with tcp:// I get this error :

```
Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
``` 

I think a feature is needed to consider protocols like mqtts because I am able to connect with broker using the same configuration when I am using npm mqtt package. I just have to add the protocol field in the config {protocol: 'mqtts'} .

**Comment by ulfox** [comment]
@kaustav1996 can you try with ssl:// instead of mqtts:// ?

**Comment by kaustav1996** [comment]
@ulfox Heyy thanks it works. I will close the issue :)
