### ISSUE TITLE
Cannot use kafka-connect-influxdb 2.1.3 with Confluent Kafka 5.5.2

### ISSUE THREAD

**Issue by afausti** [lensesio/stream-reactor#735]
# Issue Guidelines

### What version of the Stream Reactor are you reporting this issue for?

2.1.3

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
Yes, the README says Confluent 5.5.2 should work: Kafka 2.5+ (Confluent 5.5) - Stream reactor 2.0.0+

### Have you read the [docs](https://docs.lenses.io/connectors/)?
Yes.

### What is the expected behaviour?
kafka-connect-influxdb 2.1.3 should work with Confluent Kafka 5.5.2

### What was observed?

I've built `cp-kafka-connect` with the current release of  `kafka-connect-influxdb`:

```
$cat Dockerfile
FROM confluentinc/cp-kafka-connect:5.5.2
MAINTAINER afausti@lsst.org

# Add the InfluxDB Sink Connector
RUN mkdir -p /etc/landoop/jars/lib
COPY kafka-connect-influxdb-2.1.3-2.5.0-all.jar /etc/landoop/jars/lib
RUN chmod -R ag+w /etc/landoop/jars/lib
```

I have a [docker-compose setup](https://github.com/lsst-sqre/kafka-connect-manager/blob/master/tests/docker-compose.yml) that can be used to reproduce the issue.

IMPORTANT: after downloading the docker-compose.yml file, please replace the line:

```
    image: lsstsqre/cp-kafka-connect:5.5.2-0.8.2-tickets-DM-21334
```
with

```
    image: lsstsqre/cp-kafka-connect:5.5.2-0.8.2-release-2.1.3
```
to use the `cp-kafka-connect` image that includes the released version of the connector.

Please run [these steps](https://kafka-connect-manager.lsst.io/userguide.html#influxdb-sink-connector) to reproduce the bug.

### What is your Connect cluster configuration (connect-avro-distributed.properties)?

This can be inspected from the connect image, for example:
```
$ docker-compose exec connect cat ./etc/schema-registry/connect-avro-distributed.properties
```

### What is your connector properties configuration (my-connector.properties)?

This can be inspected using:
```
$ docker-compose run kafkaconnect config influxdb-sink
```

### Please provide full log files (redact and sensitive information)
When producing Avro records for Value only, I get an error like this (from the connect logs)

```
docker-compose exec schema-registry kafka-avro-console-producer --bootstrap-server broker:29092 --topic foo --property value.schema='{"type":"record", "name":"foo", "fields":[{"name":"bar","type":"string"}, {"name":"baz","type":"float"}]}'

{"bar": "John Doe", "baz": 1}
Ctrl+D
```

```
connect            | [2021-01-22 20:50:40,774] INFO Empty list of records received. (com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask)
connect            | [2021-01-22 20:50:50,774] INFO Empty list of records received. (com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask)
connect            | [2021-01-22 20:50:59,739] ERROR Encountered error argument "content" is null (com.datamountaineer.streamreactor.connect.influx.writers.InfluxDb
Writer)
connect            | java.lang.IllegalArgumentException: argument "content" is null
connect            |    at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4413)
connect            |    at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2709)
connect            |    at com.landoop.json.sql.JacksonJson$.asJson(JacksonJson.scala:35)
connect            |    at com.datamountaineer.streamreactor.connect.influx.converters.SinkRecordParser$.$anonfun$build$2(SinkRecordParser.scala:59)
connect            |    at scala.util.Try$.apply(Try.scala:213)
connect            |    at com.datamountaineer.streamreactor.connect.influx.converters.SinkRecordParser$.build(SinkRecordParser.scala:59)
connect            |    at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder.$anonfun$build$1(InfluxBatchPointsBuilder.scala:90)
connect            |    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
connect            |    at scala.collection.Iterator.foreach(Iterator.scala:943)
connect            |    at scala.collection.Iterator.foreach$(Iterator.scala:943)
connect            |    at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
connect            |    at scala.collection.IterableLike.foreach(IterableLike.scala:74)
connect            |    at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
connect            |    at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
connect            |    at scala.collection.TraversableLike.map(TraversableLike.scala:273)
connect            |    at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
connect            |    at scala.collection.AbstractTraversable.map(Traversable.scala:108)
connect            |    at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder.build(InfluxBatchPointsBuilder.scala:88)
connect            |    at com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter.write(InfluxDbWriter.scala:45)
connect            |    at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask.$anonfun$put$2(InfluxSinkTask.scala:77)
connect            |    at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask.$anonfun$put$2$adapted(InfluxSinkTask.scala:77)
connect            |    at scala.Option.foreach(Option.scala:407)
connect            |    at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask.put(InfluxSinkTask.scala:77)
connect            |    at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:549)
connect            |    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:329)
connect            |    at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
connect            |    at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
connect            |    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
connect            |    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
connect            |    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
connect            |    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
connect            |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
connect            |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
connect            |    at java.lang.Thread.run(Thread.java:748) 
```

looking at the code [SinkRecordParser.scala:59](https://github.com/lensesio/stream-reactor/blob/master/kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/converters/SinkRecordParser.scala#L59) I think it is trying to parse the record key when it shouldn't.

I tried to go further and produce a record with a key using:

```
docker-compose exec schema-registry kafka-avro-console-producer --bootstrap-server broker:29092 --topic foo  --property parse.key=true --property key.schema='{"type" : "int", "name" : "id"}' --property key.separator="|" --property value.schema='{"type":"record", "name":"foo", "fields":[{"name":"bar","type":"string"}, {"name":"baz","type":"float"}]}'

1|{"bar": "John Doe","baz": 1}
Ctrl+D
```

but then it gives another error:

```
connect            | [2021-01-22 20:43:38,396] INFO Empty list of records received. (com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask)
connect            | [2021-01-22 20:43:41,075] ERROR Encountered error Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed bet
ween tokens
connect            |  at [Source: (String)""; line: 1, column: 2] (com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter)
connect            | com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed betwee
n tokens
connect            |  at [Source: (String)""; line: 1, column: 2]
connect            |    at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
```

For the key separator I also tried TAB (default), or a regular whitespace (using `--property key.separator=" "`) but that gives a similar error.

I think the change was introduced in this PR #627, if I build the connector with the revision right before that I can successfully run the connector.

I really appreciate if someone could shed some light here. At the moment I'm stuck with an old version of the connector.

**Comment by stheppi** [comment]
Hi @afausti,
  You are producing Avro records for both Key and Value. Avro writes a first byte of 0 then the next 4 bytes for the schema id integer. So the error:
  `com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 0)`  and the source code location (it's coming with a schema of String) it looks like you don't run the connector with the `key.converter` and `value.converter` to AvroConverter. Given the data from the Kafka message comes as a STRING you might run with StringConverter (most likely) .
 Can you please confirm your connector configuration?

**Comment by afausti** [comment]
Thank you @stheppi that solves the problem, I had:

```
CONNECT_KEY_CONVERTER=org.apache.kafka.connect.storage.StringConverter
```

which I replaced with:
```
CONNECT_KEY_CONVERTER=io.confluent.connect.avro.AvroConverter
CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
```

Now the command that produces Avro records for both Key and Value works fine (after fixing the schema for the Key):
```
docker-compose exec schema-registry kafka-avro-console-producer --bootstrap-server broker:29092 --topic foo  --property parse.key=true --property key.schema='{"type" : "record", "name" : "id", "fields":[{"name":"id", "type":"int"}]}' --property value.schema='{"type":"record", "name":"foo", "fields":[{"name":"bar","type":"string",{"name":"baz","type":"float"}]}'

{"id":1}	{"bar": "John Doe","baz": 1}
Ctrl+D
```

and my first command, that produces Avro records for Value only, also works now:
```
docker-compose exec schema-registry kafka-avro-console-producer --bootstrap-server broker:29092 --topic foo --property value.schema='{"type":"record", "name":"foo", "fields":[{"name":"bar","type":"string"}, {"name":"baz","type":"float"}]}'

{"bar": "John Doe", "baz": 1}
Ctrl+D
```

Perhaps my confusion was that this last command used to work with a previous version of the connector, even with: 
```
CONNECT_KEY_CONVERTER=org.apache.kafka.connect.storage.StringConverter
```
but it now requires:
```
CONNECT_KEY_CONVERTER=io.confluent.connect.avro.AvroConverter
CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
```
if that's ok with you I think I'm good :) thanks again.

**Comment by andrewstevenson** [comment]
@afausti can we closed this issue?

**Comment by davidsloan** [comment]
Closing as it appears the problem has been solved.
