### ISSUE TITLE
Unknown configuration 'connect.hive.security.kerberos.debug'

### ISSUE THREAD

**Issue by xgadjhe** [lensesio/stream-reactor#749]
# Issue Guidelines

Please review these questions before submitting any issue?

### What version of the Stream Reactor are you reporting this issue for?
2.1.3

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
Kafka 2.6

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
Hive 3.1.0.3.1.5.134-3

### Have you read the [docs](https://docs.lenses.io/connectors/)?
yes

### What is the expected behaviour?
working Hive connector

### What was observed?
exception in logfile:

2021-03-08 13:42:55,978 INFO HiveSinkConfigDefBuilder values: 
	connect.hive.conf.dir = /opt/kafka/external-configuration/bdap-etu3
	connect.hive.database.name = kfwba
	connect.hive.fs.defaultFS = hdfs://HDE03ENNHA
	connect.hive.hdfs.conf.dir = /opt/kafka/external-configuration/bdap-etu3
	connect.hive.kcql = INSERT INTO dynatrace SELECT * FROM kfwba.dynatrace AUTOCREATE AUTOEVOLVE PARTITIONBY tenantid STOREAS ORC WITH_FLUSH_SIZE=100 WITH_TABLE_LOCATION=/data/project/kfwba
	connect.hive.metastore = thrift
	connect.hive.metastore.uris = thrift://hde02x005e.noc.fiducia.de:9083,thrift://hde02x006e.noc.fiducia.de:9083
	connect.hive.namenode.principal = null
	connect.hive.security.kerberos.auth.mode = USERPASSWORD
	connect.hive.security.kerberos.enabled = true
	connect.hive.security.kerberos.jaas = /opt/kafka/external-configuration/bdap-etu3/jaas.conf
	connect.hive.security.kerberos.jaas.entry.name = BDAP
	connect.hive.security.kerberos.krb5 = /opt/kafka/external-configuration/bdap-etu3/krb5.conf
	connect.hive.security.kerberos.password = [hidden]
	connect.hive.security.kerberos.ticket.renew.ms = 3600000
	connect.hive.security.kerberos.user = ukfwbae03e
	connect.hive.security.keytab = null
	connect.hive.security.principal = hive/_HOST@R8737.ADS.FIDUCIA.DE
	connect.progress.enabled = false
 (com.landoop.streamreactor.connect.hive.sink.config.HiveSinkConfigDefBuilder) [task-thread-etu-kfwba-dynatrace-hive-v001-0]
2021-03-08 13:42:55,981 ERROR WorkerSinkTask{id=etu-kfwba-dynatrace-hive-v001-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-etu-kfwba-dynatrace-hive-v001-0]
org.apache.kafka.common.config.ConfigException: Unknown configuration 'connect.hive.security.kerberos.debug'
	at org.apache.kafka.common.config.AbstractConfig.get(AbstractConfig.java:159)
	at org.apache.kafka.common.config.AbstractConfig.getBoolean(AbstractConfig.java:190)
	at com.landoop.streamreactor.connect.hive.kerberos.Kerberos$.from(Kerberos.scala:13)
	at com.landoop.streamreactor.connect.hive.sink.config.HiveSinkConfig$.fromProps(HiveSinkConfig.scala:90)
	at com.landoop.streamreactor.connect.hive.sink.HiveSinkTask.start(HiveSinkTask.scala:51)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:302)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

### What is your Connect cluster configuration (connect-avro-distributed.properties)?
not relevant

### What is your connector properties configuration (my-connector.properties)?
see above

### Please provide full log files (redact and sensitive information)
see above

### Suggested Fix:
Add following line in HiveSinkConfigDef.scala:31:
`    .define(KerberosDebugKey, Type.BOOLEAN, KerberosDebugDefault, Importance.MEDIUM, KerberosDebugDoc, "Security", 3, ConfigDef.Width.MEDIUM, KerberosDebugDisplay)
`

**Comment by johnathana** [comment]
@xgadjhe Thank you for the submission. Issue will be fixed with https://github.com/lensesio/stream-reactor/pull/757
