### ISSUE TITLE
scala.MatchError when reading bytes from S3 to kafka

### ISSUE THREAD

**Issue by Ozsie** [lensesio/stream-reactor#754]
# Issue Guidelines

Please review these questions before submitting any issue?

### What version of the Stream Reactor are you reporting this issue for?

2.1.3

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?

Kafka Connect: 2.6.0
Kafka: 2.7.0 (Commit:448719dc99a19793)

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?

Yes. [https://github.com/lensesio/stream-reactor/tree/master/kafka-connect-aws-s3](https://github.com/lensesio/stream-reactor/tree/master/kafka-connect-aws-s3)

### Have you read the [docs](https://docs.lenses.io/connectors/)?

Yes

### What is the expected behaviour?

Source connector reads stored binary file and delivers it to a topic

### What was observed?

Read data is matched against the wrong type, resulting in an error

```
scala.MatchError: (None,[B@33586fd2,[B@a2db496) (of class scala.Tuple3)
	at io.lenses.streamreactor.connect.aws.s3.source.S3SourceTask.convertToSourceRecord(S3SourceTask.scala:113)
	at io.lenses.streamreactor.connect.aws.s3.source.S3SourceTask.$anonfun$convertToSourceRecordList$1(S3SourceTask.scala:109)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:273)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at io.lenses.streamreactor.connect.aws.s3.source.S3SourceTask.convertToSourceRecordList(S3SourceTask.scala:109)
	at io.lenses.streamreactor.connect.aws.s3.source.S3SourceTask.$anonfun$poll$2(S3SourceTask.scala:93)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:280)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:280)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:277)
	at scala.collection.immutable.List.flatMap(List.scala:355)
	at io.lenses.streamreactor.connect.aws.s3.source.S3SourceTask.poll(S3SourceTask.scala:93)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:289)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:256)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### What is your connector properties configuration (my-connector.properties)?

Sink connector

```json
{
  "name": "S3_SINK",
  "config": {
    "connector.class": "io.lenses.streamreactor.connect.aws.s3.sink.S3SinkConnector",
    "connect.s3.kcql": "insert into bucket select * from source_topic STOREAS `Bytes_KeyAndValueWithSizes` WITH_FLUSH_COUNT = 1",
    "topics": "source_topic",
    "tasks.max": "1",
    "aws.custom.endpoint": ********,
    "aws.vhost.bucket": "true",
    "value.converter": "org.apache.kafka.connect.converters.ByteArrayConverter",
    "key.converter": "org.apache.kafka.connect.converters.ByteArrayConverter"
  }
}
```

Source connector

```json
{
  "name": "S3_SOURCE",
  "config": {
    "connector.class": "io.lenses.streamreactor.connect.aws.s3.source.S3SourceConnector",
    "tasks.max": "1",
    "connect.s3.kcql": "INSERT INTO restore_topic SELECT * from bucket STOREAS `Bytes_KeyAndValueWithSizes` WITH_FLUSH_COUNT = 1",
    "topics": "restore_topic",
    "value.converter": "org.apache.kafka.connect.converters.ByteArrayConverter",
    "key.converter": "org.apache.kafka.connect.converters.ByteArrayConverter",
    "aws.vhost.bucket": true,
    "aws.custom.endpoint": *********
  }
}
```

### Context

Data from a Kafka topic is stored in a Hitachi Vantara HCP, S3 compatible store, and then read back from said store into another topic. Changing the order of the match in `S3SourceTask` fixes the issue, but I don't know if it will have any side effects for other types.

That is, changing from

```scala
    val (schema: Option[Schema], value: AnyRef, key: Option[AnyRef]) = sourceData match {
      case SchemaAndValueSourceData(result: SchemaAndValue, _) =>
        (Some(result.schema()), result.value(), None)
      case StringSourceData(result: String, _) =>
        (None, result, None)
      case ByteArraySourceData(resultBytes, _) =>
        (None, resultBytes.value, Some(resultBytes.key))
      case _ =>
        throw new IllegalArgumentException(s"Unexpected type in convertToSourceRecord, ${sourceData.getClass}")
    }
```

to

```scala
    val (schema: Option[Schema], value: AnyRef, key: Option[AnyRef]) = sourceData match {
      case ByteArraySourceData(resultBytes, _) =>
        (None, resultBytes.value, Some(resultBytes.key))
      case SchemaAndValueSourceData(result: SchemaAndValue, _) =>
        (Some(result.schema()), result.value(), None)
      case StringSourceData(result: String, _) =>
        (None, result, None)
      case _ =>
        throw new IllegalArgumentException(s"Unexpected type in convertToSourceRecord, ${sourceData.getClass}")
    }
```

**Comment by andrewstevenson** [comment]
@davidsloan
