### ISSUE TITLE
 Illegal character [*] in path in windows machine.

### ISSUE THREAD

**Issue by politrons** [lensesio/stream-reactor#811]
Hi, 

I'm using your library `ftp-kafka-connect`,  and when I try to make an integration test adding the configuration in Mac/Linux works fine

```
		Map<String, String> configMap = new HashMap<>();
			configMap.put(FtpSourceConfig.Address(), "localhost:" + server.getPort());
			configMap.put(FtpSourceConfig.User(), "demo");
			configMap.put(FtpSourceConfig.Password(), "password");
			configMap.put(FtpSourceConfig.RefreshRate(), "PT0S");
			configMap.put(FtpSourceConfig.MonitorTail(), "/foo/:kafka_topic");
			configMap.put(FtpSourceConfig.FileMaxAge(), "PT952302H53M5.962S");
			configMap.put(FtpSourceConfig.KeyStyle(), "struct");
```

But when I execute the same test in Windows 10 fails with an error regarding the `MonitorTail` path

```
java.nio.file.InvalidPathException: Illegal character [*] in path at index 7: //foo//*

	at sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:116)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.datamountaineer.streamreactor.connect.ftp.source.MonitoredPath.<init>(FtpMonitor.scala:37)
	at com.datamountaineer.streamreactor.connect.ftp.source.FtpSourcePoller.$anonfun$monitor2topic$1(FtpSourceTask.scala:41)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:273)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at com.datamountaineer.streamreactor.connect.ftp.source.FtpSourcePoller.<init>(FtpSourceTask.scala:41)
	at it.SftpConnectIntegrationTest.lambda$sftpConverterToKafka$0(SftpConnectIntegrationTest.java:42)
	at com.github.stefanbirkner.fakesftpserver.lambda.FakeSftpServer.withSftpServer(FakeSftpServer.java:189)
	at it.SftpConnectIntegrationTest.sftpConverterToKafka(SftpConnectIntegrationTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

So it's seems related with the file system in Windows.

Any idea how to solve this?

Regards

**Comment by deanlinaras** [comment]
Windows OS is not supported currently. Our Windows users have been using WSL2 with success as an alternative.
