### ISSUE TITLE
AWS S3 Sink: Packages excluded from shadow jar cause ClassNotFoundException

### ISSUE THREAD

**Issue by oroszzsanett** [lensesio/stream-reactor#838]
Hi,

I'm trying to deploy to S3 sink into [AWS MSK Connect](https://aws.amazon.com/msk/features/msk-connect/) as a plugin. 

I'm using the shadowJar suggested in the [documentation](https://github.com/lensesio/stream-reactor/tree/4685270d18c747fa8170598972da34df7492f1f4/kafka-connect-aws-s3#building) but it is specifically excludes certain packages that are needed for the sink to work.  
At its current state the connector fails with ClassNotFoundException for several classes. 
The dependencies are excluded here: https://github.com/lensesio/stream-reactor/blob/4685270d18c747fa8170598972da34df7492f1f4/build.gradle#L146

When I rebuild the shadow jar with the above included the connector works as expected. 

Why are the packages excluded from the fat jar? 

Version: 3.0.1

Thanks!

Example stack trace, fails for this but not exclusively:
```
java.lang.NoClassDefFoundError: org/apache/avro/io/DatumWriter
[Worker-0ee7dd3da524b5f13] 	at io.confluent.connect.avro.AvroConverter.configure(AvroConverter.java:77)
[Worker-0ee7dd3da524b5f13] 	at org.apache.kafka.connect.runtime.isolation.Plugins.newConverter(Plugins.java:298)
[Worker-0ee7dd3da524b5f13] 	at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:532)
[Worker-0ee7dd3da524b5f13] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1300)
[Worker-0ee7dd3da524b5f13] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1700(DistributedHerder.java:130)
[Worker-0ee7dd3da524b5f13] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$10.call(DistributedHerder.java:1315)
[Worker-0ee7dd3da524b5f13] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$10.call(DistributedHerder.java:1311)
[Worker-0ee7dd3da524b5f13] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[Worker-0ee7dd3da524b5f13] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[Worker-0ee7dd3da524b5f13] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[Worker-0ee7dd3da524b5f13] 	at java.base/java.lang.Thread.run(Thread.java:829)
[Worker-0ee7dd3da524b5f13] Caused by: java.lang.ClassNotFoundException: org.apache.avro.io.DatumWriter
[Worker-0ee7dd3da524b5f13] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
[Worker-0ee7dd3da524b5f13] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[Worker-0ee7dd3da524b5f13] 	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
[Worker-0ee7dd3da524b5f13] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

```

**Comment by davidsloan** [comment]
Please could you let us know which version of Kafka are you using?

**Comment by davidsloan** [comment]
We currently only test with vanilla Kafka, and haven't done any testing against MSK Connect.  It's possible that those jars are bundled into Kafka however not included in MSK's version.  I think more investigation would be required for a definitive answer, but I'm glad you found a workaround.

**Comment by davidsloan** [comment]
I believe this was fixed in this PR:
https://github.com/lensesio/stream-reactor/pull/853

**Comment by devdavidkarlsson** [comment]
> 

We stumbled upon the same issues:

`Caused by: java.lang.NoClassDefFoundError: org/apache/avro/io/DatumWriter`

https://github.com/lensesio/stream-reactor/releases/download/4.0.0/kafka-connect-aws-s3-kafka-2-8-4.0.0.zip

Exceptions occur specifically when: STOREAS `Avro` or STOREAS `Parquet` is used it seems

**Comment by davidsloan** [comment]
I believe we have the solution for the issue now - would you be willing to help test it out?

**Comment by oroszzsanett** [comment]
> I believe we have the solution for the issue now - would you be willing to help test it out?

Hi. I no longer work on project where I needed this but if you attach a jar I can try to take a look

**Comment by davidsloan** [comment]
> > I believe we have the solution for the issue now - would you be willing to help test it out?
> 
> Hi. I no longer work on project where I needed this but if you attach a jar I can try to take a look

@oroszzsanett thank you.  Jar can be found here:
https://github.com/lensesio/stream-reactor/actions/runs/3985460057#artifacts

**Comment by oroszzsanett** [comment]
> > > I believe we have the solution for the issue now - would you be willing to help test it out?
> > 
> > 
> > Hi. I no longer work on project where I needed this but if you attach a jar I can try to take a look
> 
> @oroszzsanett thank you. Jar can be found here: https://github.com/lensesio/stream-reactor/actions/runs/3985460057#artifacts

I tried to test it but couldn't make it work.  It still needs the `io.confluent.connect.avro.AvroConverter` and `io.confluent.kafka.schemaregistry.client.SchemaRegistryClient` at the least I think

**Comment by huihuangc6** [comment]
I'm having the same issue using Lenses S3 sink with MSK Connect. Working mostly but when trying to save as Parquet got the following error in the logs:
[Worker-0cab04a5d0b1a43f8] Caused by: java.lang.NoClassDefFoundError: io/confluent/connect/avro/AvroData
[Worker-0cab04a5d0b1a43f8] 	at io.lenses.streamreactor.connect.aws.s3.sink.conversion.ToAvroDataConverter$.<clinit>(ToAvroDataConverter.scala:30)

Not sure why classes from Confluent Schema Registry is used here.

**Comment by pellepelster** [comment]
We were affected by the same issue, on AWS MSK, excluding the avro packages from shadin (https://github.com/lensesio/stream-reactor/compare/master...pellepelster:stream-reactor:master) fixed the issue for us. Unfortunately the reasoning for shifting the packages to `lshaded` os not clear to me, which makes it hard to propose a fix.

**Comment by davidsloan** [comment]
> We were affected by the same issue, on AWS MSK. Excluding the avro packages from shading ([master...pellepelster:stream-reactor:master](https://github.com/lensesio/stream-reactor/compare/master...pellepelster:stream-reactor:master)) fixed the issue for us. Unfortunately the reasoning for shifting the packages to `lshaded` os not clear to me, which makes it hard to propose a fix.

@pellepelster They are shaded to avoid conflicting with the jars that kafka ships with.

MSK is a different beast entirely and we still need to work out a strategy for this.
