### ISSUE TITLE
Unsupported record 443:java.lang.Short if message includes header values (S3 SinkConnector)

### ISSUE THREAD

**Issue by Alexander-ac** [lensesio/stream-reactor#860]
Hi guys, I'm getting the following error message and I can't find any cause for it. **I have 
noticed that if the message contains some header values**, this error occurs. Can I ignore header properties?
Can you help me please....

[2022-06-08 19:31:15,106] ERROR WorkerSinkTask{id=S3SinkConnector-8} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:184)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:609)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:329)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:182)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:231)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.connect.errors.ConnectException: org.apache.kafka.connect.errors.ConnectException: Unsupported record 443:java.lang.Short
        at com.datamountaineer.streamreactor.common.errors.ThrowErrorPolicy.handle(ErrorPolicy.scala:59)
        at com.datamountaineer.streamreactor.common.errors.ErrorHandler.handleError(ErrorHandler.scala:85)
        at com.datamountaineer.streamreactor.common.errors.ErrorHandler.handleTry(ErrorHandler.scala:66)
        at com.datamountaineer.streamreactor.common.errors.ErrorHandler.handleTry$(ErrorHandler.scala:48)
        at io.lenses.streamreactor.connect.aws.s3.sink.S3SinkTask.handleTry(S3SinkTask.scala:38)
        at io.lenses.streamreactor.connect.aws.s3.sink.S3SinkTask.put(S3SinkTask.scala:144)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
        ... 10 more
Caused by: org.apache.kafka.connect.errors.ConnectException: Unsupported record 443:java.lang.Short
        at io.lenses.streamreactor.connect.aws.s3.sink.conversion.ValueToSinkDataConverter$.apply(ValueToSinkDataConverter.scala:43)
        at io.lenses.streamreactor.connect.aws.s3.sink.conversion.HeaderToStringConverter$.headerValueToString(HeaderToStringConverter.scala:32)
        at io.lenses.streamreactor.connect.aws.s3.sink.conversion.HeaderToStringConverter$.$anonfun$apply$1(HeaderToStringConverter.scala:29)
        at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:99)
        at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:86)
        at scala.collection.convert.JavaCollectionWrappers$JIterableWrapper.map(JavaCollectionWrappers.scala:58)
        at io.lenses.streamreactor.connect.aws.s3.sink.conversion.HeaderToStringConverter$.apply(HeaderToStringConverter.scala:29)
        at io.lenses.streamreactor.connect.aws.s3.sink.S3SinkTask.$anonfun$put$4(S3SinkTask.scala:160)
        at io.lenses.streamreactor.connect.aws.s3.sink.S3SinkTask.$anonfun$put$4$adapted(S3SinkTask.scala:154)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
        at io.lenses.streamreactor.connect.aws.s3.sink.S3SinkTask.$anonfun$put$1(S3SinkTask.scala:154)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.Try$.apply(Try.scala:210)
        ... 12 more

My Config file:

name=S3SinkConnector
connector.class=io.lenses.streamreactor.connect.aws.s3.sink.S3SinkConnector
tasks.max=13
key.converter.schemas.enable=false
connect.s3.kcql=INSERT INTO XXXXXX-dev-kafka-backup SELECT * FROM MONITORING_V01 STOREAS `JSON` WITH_FLUSH_COUNT = 1
connect.s3.aws.region=eu-central-1
topics=MONITORING_V01
schema.enable=false
errors.log.enable=true
key.converter.schemas.enable=false
value.converter.schemas.enable=false
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter

**Comment by davidsloan** [comment]
This has gone into the 4.1.0 release - thanks for reporting the issue!
