### ISSUE TITLE
Kudu Sink: java.lang.NoClassDefFoundError: io/confluent/kafka/schemaregistry/client/rest/RestService

### ISSUE THREAD

**Issue by darktaiga01** [lensesio/stream-reactor#905]
### What version of the Stream Reactor are you reporting this issue for?
4.0.0. I downloaded kafka-connect-kudu-kafka-3-1-4.0.0.zip

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
Yes, I'm using Kafka and Kafka Connect 3.1

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
Yes, Kudu 1.16.0

### Have you read the [docs](https://docs.lenses.io/connectors/)?
Yes

### What is your Connect cluster configuration (connect-avro-distributed.properties)?

```
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
```

I'm not using Registry Schema

### What is your connector properties configuration (my-connector.properties)?

```
{
	"connector.class": "com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkConnector",
	"connect.kudu.kcql": "INSERT INTO default.orders SELECT * FROM orders",
	"tasks.max": "1",
	"topics": "orders",
	"name": "kudu-connector",
	"connect.kudu.master": "xxx:7051"
}
```

### Please provide full log files (redact and sensitive information)

```
[2023-01-10 16:08:27,106] INFO [kudu-connector|task-0] [Consumer clientId=connector-consumer-kudu-connector-0, groupId=connect-kudu-connector] Subscribed to topic(s): orders (org.apache.kafka.clients.consumer.KafkaConsumer:966)
[2023-01-10 16:08:27,109] INFO [kudu-connector|task-0] 
    __                    __
   / /   ____ _____  ____/ /___  ____  ____
  / /   / __ `/ __ \/ __  / __ \/ __ \/ __ \
 / /___/ /_/ / / / / /_/ / /_/ / /_/ / /_/ /
/_____/\__,_/_/ /_/\__,_/\____/\____/ .___/
                                   /_/
       __ __          __      _____ _       __
      / //_/_  ______/ /_  __/ ___/(_)___  / /__
     / ,< / / / / __  / / / /\__ \/ / __ \/ //_/
    / /| / /_/ / /_/ / /_/ /___/ / / / / / ,<
   /_/ |_\__,_/\__,_/\__,_//____/_/_/ /_/_/|_| by Andrew Stevenson

 null (com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkTask:49)
[2023-01-10 16:08:27,109] INFO [kudu-connector|task-0] 
StreamReactor-Version:       null
Kafka-Version:               null
Git-Repo:                    null
Git-Commit-Hash:             null
Git-Tag:                     null
StreamReactor-Docs:          null
       (com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkTask:51)
[2023-01-10 16:08:27,109] INFO [kudu-connector|task-0] KuduConfig values: 
	connect.kudu.error.policy = THROW
	connect.kudu.kcql = INSERT INTO default.orders SELECT * FROM orders
	connect.kudu.master = xxx:7051
	connect.kudu.max.retries = 20
	connect.kudu.mutation.buffer.space = 1000
	connect.kudu.retry.interval = 60000
	connect.kudu.schema.registry.url = http://localhost:8081
	connect.kudu.write.flush.mode = SYNC
	connect.progress.enabled = false
 (com.datamountaineer.streamreactor.connect.kudu.config.KuduConfig:376)
[2023-01-10 16:08:27,113] INFO [kudu-connector|task-0] Connecting to Kudu Master at 172.16.38.120:7051 (com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter$:52)
[2023-01-10 16:08:27,117] INFO [kudu-connector|task-0] Initialising Kudu writer (com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter:64)
[2023-01-10 16:08:27,138] INFO [kudu-connector|task-0] Found the following tables in Kudu, default.test_kafka_revenue_,default.erp_masterdata_pm_store,default.test_table_sang,default.sang1672990829871,default.orders,default.erp_erp_pm_begininstockinfo,default.promotionid,default.erp_pm_inputvoucher_filtered,default.banned_ingredient,default.erp_pm_outputvoucher_filtered2,default.erp_masterdata_pm_outputtype (com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$:57)
[2023-01-10 16:08:27,140] ERROR [kudu-connector|task-0] WorkerSinkTask{id=kudu-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:195)
**java.lang.NoClassDefFoundError: io/confluent/kafka/schemaregistry/client/rest/RestService**
	at com.datamountaineer.streamreactor.common.schemas.SchemaRegistry$.getSubjects(SchemaRegistry.scala:65)
	at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$.createTables(DbHandler.scala:104)
	at com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter.$anonfun$new$1(KuduWriter.scala:66)
	at scala.util.Try$.apply(Try.scala:210)
	at com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter.<init>(KuduWriter.scala:66)
	at com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter$.apply(KuduWriter.scala:54)
	at com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkTask.start(KuduSinkTask.scala:65)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:312)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: io.confluent.kafka.schemaregistry.client.rest.RestService
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:103)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 15 more
[2023-01-10 16:08:27,141] INFO [kudu-connector|task-0] Stopping Kudu sink. (com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkTask:85)
[2023-01-10 16:08:27,141] INFO [kudu-connector|task-0] [Consumer clientId=connector-consumer-kudu-connector-0, groupId=connect-kudu-connector] Resetting generation due to: consumer pro-actively leaving the group (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-01-10 16:08:27,141] INFO [kudu-connector|task-0] [Consumer clientId=connector-consumer-kudu-connector-0, groupId=connect-kudu-connector] Request joining group due to: consumer pro-actively leaving the group (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:1000)
[2023-01-10 16:08:27,141] INFO [kudu-connector|task-0] Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:659)
[2023-01-10 16:08:27,142] INFO [kudu-connector|task-0] Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:663)
[2023-01-10 16:08:27,142] INFO [kudu-connector|task-0] Metrics reporters closed (org.apache.kafka.common.metrics.Metrics:669)
[2023-01-10 16:08:27,142] INFO [kudu-connector|task-0] App info kafka.consumer for connector-consumer-kudu-connector-0 unregistered (org.apache.kafka.common.utils.AppInfoParser:83)
```

### What I did

I've created table on Kudu through Impala, so I don't use AUTOCREATE
I create a message with value 

```
{
	"id": 1,
	"created": "2016-05-06 13:53:00",
	"product": "OP-DAX-P-20150201-95.7",
	"price": 94.2,
	"qty": 100
}
```
and without value.schema. I think the error is due to missing schema registry libs in connectors jar. But I didn't use Schema Registry, so I don't understand why it needs schema-registry libs.

Thanks for reading

**Comment by darktaiga01** [comment]
After putting this line into config file, the problem has been solved. 
```
value.converter.auto.register.schemas=false
```

But I get other error, so I will create other issues. Thanks
